In [8]:
import numpy as np

作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [21]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

with open('homework.npz', 'wb') as f:
    np.savez(f,array1=array1,array2=array2)

In [22]:
with open('homework.npz', 'rb') as f:
    a = np.load(f)
    b = np.load(f)
print(a, b)

<numpy.lib.npyio.NpzFile object at 0x1184e8f10> <numpy.lib.npyio.NpzFile object at 0x1184d0a50>


In [26]:
npzfile = np.load('homework.npz')
type(npzfile)

numpy.lib.npyio.NpzFile

In [27]:
print(npzfile['array1'])
print(npzfile['array2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [ ]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

In [30]:
array3=np.array([23,45,67,89])

with open('homework_2.npz', 'wb') as f:
    np.savez(f,array1=array1,array2=array2,array3=array3)

In [31]:
with open('homework_2.npz', 'rb') as f:
    a = np.load(f)
    b = np.load(f)
    c = np.load(f)
print(a, b,c)

<numpy.lib.npyio.NpzFile object at 0x1184b9a90> <numpy.lib.npyio.NpzFile object at 0x1184e8f10> <numpy.lib.npyio.NpzFile object at 0x1184deb50>


In [32]:
npzfile = np.load('homework.npz')
type(npzfile)

numpy.lib.npyio.NpzFile

In [33]:
print(npzfile['array1'])
print(npzfile['array2'])
print(npzfile['array3'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[23 45 67 89]
